language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'antispam-js' ]; then cd .. && eval "mv $currentfolder antispam-js" && cd antispam-js; fi
